export const comments = [
  "A captivating read that kept me engaged from start to finish.",
  "The author's vivid descriptions transported me into the story's world.",
  "An intriguing plot with unexpected twists and turns.",
  "The character development was exceptional, making them feel real and relatable.",
  "A thought-provoking narrative that lingered in my mind long after I finished the book.",
  "The pacing was perfect, maintaining suspense throughout the story.",
  "A beautifully written prose that was a joy to read.",
  "The themes explored in this book were both timely and universal.",
  "An emotional rollercoaster that tugged at my heartstrings.",
  "The world-building was incredibly detailed and immersive.",
  "A page-turner that I couldn't put down until I reached the last page.",
  "The dialogue felt authentic and added depth to the characters.",
  "A unique perspective on a familiar topic, offering fresh insights.",
  "The author's research shines through, adding credibility to the narrative.",
  "A perfect blend of humor and drama that kept me entertained throughout.",
];
